language: node_js
dist: focal
node_js:
  - '18'
before_install:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > packages/deskpro-messenger/.npmrc
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > packages/deskpro-messenger-loader/.npmrc
cache:
  directories:
    - packages/deskpro-messenger/node_modules
install:
  - yarn
script: yarn build
deploy:
  - provider: script
    skip_cleanup: true
    script: npm run publish-npm -- $(node bin/lerna-version.js)
    on:
      tags: true
