language: node_js
node_js:
- '8'
before_deploy:
- npm run build-storybook
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep-history: true
    local-dir: storybook-static
    on:
      branch: master