language: node_js
node_js:
  - '16'
before_install:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > packages/deskpro-messenger/.npmrc
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > packages/deskpro-messenger-loader/.npmrc
cache:
  directories:
    - packages/deskpro-messenger/node_modules
install:
  - yarn
  - yarn bootstrap
script: yarn lerna run build
before_deploy:
  - yarn lerna run build-storybook
  - cp packages/deskpro-messenger/build/assets/styles.css* packages/deskpro-messenger/storybook-static/assets/
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep-history: true
    local-dir: packages/deskpro-messenger/storybook-static
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: npm run publish-npm -- $(node bin/lerna-version.js)
    on:
      tags: true
